[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hpke = "0.9.0"
rand = "0.8.3"
strobe-rs = "0.7.0"
concat-kdf = "0.1.0"
sha2 = { version = "0.10", default-features = false }